/*----------------------------------------------------------------------
Oberon2 compiler for x86
Copyright (c) 2012 Evgeniy Grigorievitch Philippov
Distributed under the terms of GNU General Public License, v.3 or later

Compiler Generator Coco/R,
Copyright (c) 1990, 2004 Hanspeter Moessenboeck, University of Linz
extended by M. Loeberbauer & A. Woess, Univ. of Linz
ported to C++ by Csaba Balazs, University of Szeged
with improvements by Pat Terry, Rhodes University

This program is free software; you can redistribute it and/or modify it 
under the terms of the GNU General Public License as published by the 
Free Software Foundation; either version 2, or (at your option) any 
later version.

This program is distributed in the hope that it will be useful, but 
WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY 
or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License 
for more details.

You should have received a copy of the GNU General Public License along 
with this program; if not, write to the Free Software Foundation, Inc., 
59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

As an exception, it is allowed to write an extension of Coco/R that is
used as a plugin in non-free software.

If not otherwise stated, any source code generated by Coco/R (other than 
Coco/R itself) does not fall under the GNU General Public License.
-----------------------------------------------------------------------*/


#include <wchar.h>
#include "Parser.h"
#include "Scanner.h"


namespace Oberon {


void Parser::SynErr(int n) {
	//if (errDist >= minErrDist)
		errors->SynErr(la->line, la->col, n);
	errDist = 0;
}

void Parser::SemErr(const wchar_t* msg) {
	//if (errDist >= minErrDist)
		errors->Error(t->line, t->col, msg);
	errDist = 0;
}

void Parser::Get() {
	for (;;) {
		t = la;
		la = scanner->Scan();
		if (la->kind <= maxT) { ++errDist; break; }

		if (dummyToken != t) {
			dummyToken->kind = t->kind;
			dummyToken->pos = t->pos;
			dummyToken->col = t->col;
			dummyToken->line = t->line;
			dummyToken->next = NULL;
			coco_string_delete(dummyToken->val);
			dummyToken->val = coco_string_create(t->val);
			t = dummyToken;
		}
		la = t;
	}
}

void Parser::Expect(int n) {
	if (la->kind==n) Get(); else { SynErr(n); }
}

void Parser::ExpectWeak(int n, int follow) {
	if (la->kind == n) Get();
	else {
		SynErr(n);
		while (!StartOf(follow)) Get();
	}
}

bool Parser::WeakSeparator(int n, int syFol, int repFol) {
	if (la->kind == n) {Get(); return true;}
	else if (StartOf(repFol)) {return false;}
	else {
		SynErr(n);
		while (!(StartOf(syFol) || StartOf(repFol) || StartOf(0))) {
			Get();
		}
		return StartOf(syFol);
	}
}

void Parser::number(numberRecord &r) {
		if (la->kind == _integer) {
			IntegerRec(r.tokenString);
			r.numtype=num_int; 
		} else if (la->kind == _real) {
			RealRec(r.tokenString);
			r.numtype=num_real; 
		} else SynErr(68);
}

void Parser::IntegerRec(wchar_t* &tok) {
		Integer(tok);
}

void Parser::RealRec(wchar_t* &tok) {
		Real(tok);
}

void Parser::Relation(int &op) {
		op = illegal_operator; 
		switch (la->kind) {
		case 7 /* "=" */: {
			Get();
			op = equals; 
			break;
		}
		case 8 /* "#" */: {
			Get();
			op = notEquals; 
			break;
		}
		case 9 /* "<" */: {
			Get();
			op = less; 
			break;
		}
		case 10 /* "<=" */: {
			Get();
			op = lessOrEqual; 
			break;
		}
		case 11 /* ">" */: {
			Get();
			op = greater; 
			break;
		}
		case 12 /* ">=" */: {
			Get();
			op = greaterOrEqual; 
			break;
		}
		case 13 /* "IN" */: {
			Get();
			op = in; 
			break;
		}
		case 14 /* "IS" */: {
			Get();
			op = is; 
			break;
		}
		default: SynErr(69); break;
		}
}

void Parser::AddOp(int &op) {
		op = illegal_operator; 
		if (la->kind == 15 /* "+" */) {
			Get();
			op = plus; 
		} else if (la->kind == 16 /* "-" */) {
			Get();
			op = minus; 
		} else if (la->kind == 17 /* "OR" */) {
			Get();
			op = orOperation; 
		} else SynErr(70);
}

void Parser::MulOp(int &op) {
		op = illegal_operator; 
		if (la->kind == 18 /* "*" */) {
			Get();
			op = times; 
		} else if (la->kind == 19 /* "/" */) {
			Get();
			op = slash; 
		} else if (la->kind == 20 /* "DIV" */) {
			Get();
			op = divOp; 
		} else if (la->kind == 21 /* "MOD" */) {
			Get();
			op = modOp; 
		} else if (la->kind == 22 /* "&" */) {
			Get();
			op = ampersand; 
		} else SynErr(71);
}

void Parser::Expr(ExprRecord &expr) {
		SimpleExpr(expr.lhs);
		if (StartOf(1)) {
			expr.opAndRhsPresent=true; 
			Relation(expr.op);
			SimpleExpr(expr.rhs);
		} else if (StartOf(2)) {
			expr.opAndRhsPresent=false; 
		} else SynErr(72);
}

void Parser::SimpleExpr(SimpleExprRecord &e) {
		if (StartOf(3)) {
			if (StartOf(4)) {
			} else {
				Get();
			}
			e.minus=false; 
		} else if (la->kind == 16 /* "-" */) {
			Get();
			e.minus=true; 
		} else SynErr(73);
		Term(e.term);
		if (StartOf(5)) {
			e.nullOrNextSimpleExprAddOpRecord=0; 
		} else if (la->kind == 15 /* "+" */ || la->kind == 16 /* "-" */ || la->kind == 17 /* "OR" */) {
			e.nullOrNextSimpleExprAddOpRecord=new SimpleExprAddOpRecord(); abortIfNull(e.nullOrNextSimpleExprAddOpRecord); 
			SimpleExprAddOpClause(*e.nullOrNextSimpleExprAddOpRecord);
		} else SynErr(74);
}

void Parser::ConstExpr(ConstExprRecord &cexpr) {
		cexpr.valueHasBeenCalculated=false; 
		Expr(cexpr.expr);
}

void Parser::ModuleImportEntry(ModuleImportEntryRecord &r) {
		Ident(r.lhs);
		if (la->kind == 24 /* "," */ || la->kind == 26 /* ";" */) {
			r.rhsPresent=false; 
		} else if (la->kind == 23 /* ":=" */) {
			r.rhsPresent=true; 
			Get();
			Ident(r.rhs);
		} else SynErr(75);
}

void Parser::Ident(wchar_t* &tok) {
		Expect(_ident);
		tok = coco_string_create(t->val); 
}

void Parser::ModuleImportEntryList(ImportListRecord &r) {
		ModuleImportEntry(r.moduleImportEntry);
		if (la->kind == 26 /* ";" */) {
			r.nullOrPtrToNextModuleImportEntriesList=0; 
		} else if (la->kind == 24 /* "," */) {
			r.nullOrPtrToNextModuleImportEntriesList=new ImportListRecord(); abortIfNull(r.nullOrPtrToNextModuleImportEntriesList); 
			Get();
			ModuleImportEntryList(*(r.nullOrPtrToNextModuleImportEntriesList));
		} else SynErr(76);
}

void Parser::ImportList(ImportListRecord &r) {
		Expect(25 /* "IMPORT" */);
		ModuleImportEntryList(r);
		Expect(26 /* ";" */);
}

void Parser::DeclSeqConstDeclListMandatory(DeclSeqConstDeclListMandatoryRecord &r) {
		ConstDecl(r.constDecl);
		Expect(26 /* ";" */);
		if (StartOf(6)) {
			r.nullOrPtrToNextDeclSeqConstDeclListMandatory=0; 
		} else if (la->kind == _ident) {
			r.nullOrPtrToNextDeclSeqConstDeclListMandatory=new DeclSeqConstDeclListMandatoryRecord(); 
			abortIfNull(r.nullOrPtrToNextDeclSeqConstDeclListMandatory);
			
			DeclSeqConstDeclListMandatory(*(r.nullOrPtrToNextDeclSeqConstDeclListMandatory));
		} else SynErr(77);
}

void Parser::ConstDecl(ConstDeclRecord &r) {
		IdentDef(r.identDef);
		Expect(7 /* "=" */);
		ConstExpr(r.expr);
}

void Parser::DeclSeqConstDeclList(DeclSeqConstDeclListRecord &r) {
		if (StartOf(6)) {
			r.specified=false; 
		} else if (la->kind == _ident) {
			r.specified=true; 
			DeclSeqConstDeclListMandatory(r.constDecls);
		} else SynErr(78);
}

void Parser::DeclSeqTypeDeclListMandatory(DeclSeqTypeDeclListMandatoryRecord &r) {
		TypeDecl(r.typeDecl);
		Expect(26 /* ";" */);
		if (StartOf(6)) {
			r.nullOrPtrToNextDeclSeqTypeDeclListMandatory=0; 
		} else if (la->kind == _ident) {
			r.nullOrPtrToNextDeclSeqTypeDeclListMandatory=new DeclSeqTypeDeclListMandatoryRecord(); 
			abortIfNull(r.nullOrPtrToNextDeclSeqTypeDeclListMandatory);
			
			DeclSeqTypeDeclListMandatory(*(r.nullOrPtrToNextDeclSeqTypeDeclListMandatory));
		} else SynErr(79);
}

void Parser::TypeDecl(TypeDeclRecord &r) {
		IdentDef(r.identDef);
		Expect(7 /* "=" */);
		Type(r.typePtr);
}

void Parser::DeclSeqTypeDeclList(DeclSeqTypeDeclListRecord &r) {
		if (StartOf(6)) {
			r.specified=false; 
		} else if (la->kind == _ident) {
			r.specified=true; 
			DeclSeqTypeDeclListMandatory(r.typeDecls);
		} else SynErr(80);
}

void Parser::DeclSeqVarDeclListMandatory(DeclSeqVarDeclListMandatoryRecord &r) {
		VarDecl(r.varDecl);
		Expect(26 /* ";" */);
		if (StartOf(6)) {
			r.nullOrPtrToNextDeclSeqVarDeclListMandatory=0; 
		} else if (la->kind == _ident) {
			r.nullOrPtrToNextDeclSeqVarDeclListMandatory=new DeclSeqVarDeclListMandatoryRecord(); 
			abortIfNull(r.nullOrPtrToNextDeclSeqVarDeclListMandatory);
			
			DeclSeqVarDeclListMandatory(*(r.nullOrPtrToNextDeclSeqVarDeclListMandatory));
		} else SynErr(81);
}

void Parser::VarDecl(VarDeclRecord &r) {
		IdentList(r.identList);
		Expect(31 /* ":" */);
		Type(r.typePtr);
}

void Parser::DeclSeqVarDeclList(DeclSeqVarDeclListRecord &r) {
		if (StartOf(6)) {
			r.specified=false; 
		} else if (la->kind == _ident) {
			r.specified=true; 
			DeclSeqVarDeclListMandatory(r.varDecls);
		} else SynErr(82);
}

void Parser::DeclSeqConstTypeVarListMandatory(DeclSeqConstTypeVarListMandatoryRecord &r) {
		if (la->kind == 27 /* "CONST" */) {
			Get();
			DeclSeqConstDeclList(r.constDeclList);
			r.decl_variant=decl_const; 
		} else if (la->kind == 28 /* "TYPE" */) {
			Get();
			DeclSeqTypeDeclList(r.typeDeclList);
			r.decl_variant=decl_type; 
		} else if (la->kind == 29 /* "VAR" */) {
			Get();
			DeclSeqVarDeclList(r.varDeclList);
			r.decl_variant=decl_var; 
		} else SynErr(83);
		if (la->kind == 30 /* "PROCEDURE" */ || la->kind == 32 /* "BEGIN" */ || la->kind == 33 /* "END" */) {
			r.next=0; 
		} else if (la->kind == 27 /* "CONST" */ || la->kind == 28 /* "TYPE" */ || la->kind == 29 /* "VAR" */) {
			r.next=new DeclSeqConstTypeVarListMandatoryRecord(); abortIfNull(r.next); 
			DeclSeqConstTypeVarListMandatory(*(r.next));
		} else SynErr(84);
}

void Parser::DeclSeqConstTypeVarList(DeclSeqConstTypeVarListRecord &r) {
		if (la->kind == 30 /* "PROCEDURE" */ || la->kind == 32 /* "BEGIN" */ || la->kind == 33 /* "END" */) {
			r.specified=false; 
		} else if (la->kind == 27 /* "CONST" */ || la->kind == 28 /* "TYPE" */ || la->kind == 29 /* "VAR" */) {
			r.specified=true; 
			DeclSeqConstTypeVarListMandatory(r.constTypeVarList);
		} else SynErr(85);
}

void Parser::DeclSeqProcDeclFwdDeclListMandatory(DeclSeqProcDeclFwdDeclListMandatoryRecord &r) {
		Expect(30 /* "PROCEDURE" */);
		if (la->kind == _ident || la->kind == 35 /* "(" */) {
			ProcDecl(r.procDecl);
			r.decl_variant=decl_proc; 
		} else if (la->kind == 34 /* "^" */) {
			ForwardDecl(r.fwdDecl);
			r.decl_variant=decl_fwd; 
		} else SynErr(86);
		Expect(26 /* ";" */);
		if (la->kind == 32 /* "BEGIN" */ || la->kind == 33 /* "END" */) {
			r.next=0; 
		} else if (la->kind == 30 /* "PROCEDURE" */) {
			r.next=new DeclSeqProcDeclFwdDeclListMandatoryRecord(); abortIfNull(r.next); 
			DeclSeqProcDeclFwdDeclListMandatory(*(r.next));
		} else SynErr(87);
}

void Parser::ProcDecl(ProcDeclRecord &r) {
		identRec endName; 
		OptionalReceiver(r.optionalReceiver);
		IdentDef(r.identDef);
		OptionalFormalPars(r.optionalFormalPars);
		Expect(26 /* ";" */);
		r.declSeqPtr=new DeclSeqRecord(); abortIfNull(r.declSeqPtr); 
		DeclSeq(*(r.declSeqPtr));
		if (la->kind == 33 /* "END" */) {
			r.procBodySpecifiedHere=false; 
		} else if (la->kind == 32 /* "BEGIN" */) {
			r.procBodySpecifiedHere=true; 
			Get();
			StatementSeq(r.procBodyStmtSeq);
		} else SynErr(88);
		Expect(33 /* "END" */);
		Ident(endName);
		if(!coco_string_equal(endName, r.identDef.ident_)){
		Err(L"PROCEDURE identDef ... END ident: idents do not match."); 
		} 
		
}

void Parser::ForwardDecl(ForwardDeclRecord &r) {
		Expect(34 /* "^" */);
		OptionalReceiver(r.optionalReceiver);
		IdentDef(r.identDef);
		OptionalFormalPars(r.optionalFormalPars);
}

void Parser::DeclSeqProcDeclFwdDeclList(DeclSeqProcDeclFwdDeclListRecord &r) {
		if (la->kind == 32 /* "BEGIN" */ || la->kind == 33 /* "END" */) {
			r.specified=false; 
		} else if (la->kind == 30 /* "PROCEDURE" */) {
			r.specified=true; 
			DeclSeqProcDeclFwdDeclListMandatory(r.procDeclFwdDeclList);
		} else SynErr(89);
}

void Parser::DeclSeq(DeclSeqRecord &r) {
		DeclSeqConstTypeVarList(r.ctvlist);
		DeclSeqProcDeclFwdDeclList(r.pflist);
}

void Parser::IdentDef(IdentDefRecord &r) {
		IdentRec(r.ident_);
		if (StartOf(7)) {
			r.modifier=modifier_none; 
		} else if (la->kind == 18 /* "*" */) {
			Get();
			r.modifier=modifier_star; 
		} else if (la->kind == 16 /* "-" */) {
			Get();
			r.modifier=modifier_minus; 
		} else SynErr(90);
}

void Parser::Type(TypeRecord *&ptrToTypeRecord) {
		ExprRecord expr; ConstExprRecord cexpr;
		if (la->kind == _ident) {
			Qualident();
		} else if (la->kind == 37 /* "ARRAY" */) {
			Get();
			if (StartOf(8)) {
				ConstExpr(cexpr1);
				while (la->kind == 24 /* "," */) {
					Get();
					ConstExpr(cexprN);
				}
			}
			Expect(38 /* "OF" */);
			Type(type);
		} else if (la->kind == 39 /* "RECORD" */) {
			Get();
			if (la->kind == 35 /* "(" */) {
				Get();
				Qualident();
				Expect(36 /* ")" */);
			}
			FieldList(recordFieldsList1);
			while (la->kind == 26 /* ";" */) {
				Get();
				FieldList(recordFieldsListN);
			}
			Expect(33 /* "END" */);
		} else if (la->kind == 40 /* "POINTER" */) {
			Get();
			Expect(41 /* "TO" */);
			Type(type);
		} else if (la->kind == 30 /* "PROCEDURE" */) {
			Get();
			if (la->kind == 35 /* "(" */) {
				FormalPars(formalPars);
			}
		} else SynErr(91);
}

void Parser::IdentList(IdentListRecord &r) {
		IdentDef(r.identDef);
		if (la->kind == 31 /* ":" */) {
			r.nullOrCommaIdentList=0; 
		} else if (la->kind == 24 /* "," */) {
			r.nullOrCommaIdentList=new IdentListRecord(); abortIfNull(r.nullOrCommaIdentList); 
			Get();
			IdentList(*(r.nullOrCommaExprList));
		} else SynErr(92);
}

void Parser::OptionalReceiver(OptionalReceiverRecord &r) {
		if (la->kind == _ident) {
			r.receiverSpecified=false; 
		} else if (la->kind == 35 /* "(" */) {
			r.receiverSpecified=true; 
			Receiver(r.receiver);
		} else SynErr(93);
}

void Parser::Receiver(ReceiverRecord &r) {
		Expect(35 /* "(" */);
		if (la->kind == _ident) {
			r.varSpecified=false; 
		} else if (la->kind == 29 /* "VAR" */) {
			r.varSpecified=true; 
			Get();
		} else SynErr(94);
		Ident(r.leftIdent);
		Expect(31 /* ":" */);
		Ident(r.rightIdent);
		Expect(36 /* ")" */);
}

void Parser::OptionalFormalPars(OptionalFormalParsRecord &r) {
		if (la->kind == 26 /* ";" */) {
			r.formalParsSpecified=false; 
		} else if (la->kind == 35 /* "(" */) {
			r.formalParsSpecified=true; 
			FormalPars(r.formalPars);
		} else SynErr(95);
}

void Parser::FormalPars(FormalParsRecord &r) {
		Expect(35 /* "(" */);
		if (la->kind == _ident || la->kind == 29 /* "VAR" */) {
			FPSection();
			while (la->kind == 26 /* ";" */) {
				Get();
				FPSection();
			}
		}
		Expect(36 /* ")" */);
		if (la->kind == 31 /* ":" */) {
			Get();
			Qualident();
		}
}

void Parser::StatementSeq(StatementSeqRecord &r) {
		Statement(r.statement);
		if (StartOf(9)) {
			r.nullOrPtrToNextStatementSeq=0; 
		} else if (la->kind == 26 /* ";" */) {
			r.nullOrPtrToNextStatementSeq=new StatementSeqRecord(); abortIfNull(r.nullOrPtrToNextStatementSeq); 
			Get();
			StatementSeq(*(r.nullOrPtrToNextStatementSeq));
		} else SynErr(96);
}

void Parser::FPSection() {
		if (la->kind == 29 /* "VAR" */) {
			Get();
		}
		Expect(_ident);
		while (la->kind == 24 /* "," */) {
			Get();
			Expect(_ident);
		}
		Expect(31 /* ":" */);
		Type(type);
}

void Parser::Qualident() {
		Expect(_ident);
		if (la->kind == 45 /* "." */) {
			Get();
			Expect(_ident);
		}
}

void Parser::FieldList(FieldListRecord &r) {
		if (la->kind == 26 /* ";" */ || la->kind == 33 /* "END" */) {
			r.fieldsPresent=false; 
		} else if (la->kind == _ident) {
			r.fieldsPresent=true; 
			IdentList(r.identList);
			Expect(31 /* ":" */);
			Type(r.typePtr);
		} else SynErr(97);
}

void Parser::Statement(StatementRecord*&ptrToStmtRecord) {
		ExprRecord expr; 
		if (StartOf(10)) {
			switch (la->kind) {
			case _ident: case _string: case _integer: case _real: case _character: case 15 /* "+" */: case 16 /* "-" */: case 35 /* "(" */: case 43 /* "NIL" */: case 44 /* "~" */: case 48 /* "{" */: {
				Expr(expr);
				if (la->kind == 23 /* ":=" */) {
					Get();
					Expr(expr);
				}
				break;
			}
			case 50 /* "IF" */: {
				Get();
				Expr(expr);
				Expect(51 /* "THEN" */);
				StatementSeq(thenStmtSeq);
				while (la->kind == 52 /* "ELSIF" */) {
					Get();
					Expr(expr);
					Expect(51 /* "THEN" */);
					StatementSeq(elsifThenStatementSeq);
				}
				if (la->kind == 53 /* "ELSE" */) {
					Get();
					StatementSeq(statementSeqELSE);
				}
				Expect(33 /* "END" */);
				break;
			}
			case 54 /* "CASE" */: {
				Get();
				Expr(expr);
				Expect(38 /* "OF" */);
				Case();
				while (la->kind == 55 /* "|" */) {
					Get();
					Case();
				}
				if (la->kind == 53 /* "ELSE" */) {
					Get();
					StatementSeq(statementSeqELSE);
				}
				Expect(33 /* "END" */);
				break;
			}
			case 56 /* "WHILE" */: {
				Get();
				Expr(expr);
				Expect(57 /* "DO" */);
				StatementSeq(whileBodyStatementSeq);
				Expect(33 /* "END" */);
				break;
			}
			case 58 /* "REPEAT" */: {
				Get();
				StatementSeq(repeatBodyStatementSeq);
				Expect(59 /* "UNTIL" */);
				Expr(expr);
				break;
			}
			case 60 /* "FOR" */: {
				Get();
				Ident(forCounterVariableName);
				Expect(23 /* ":=" */);
				Expr(expr);
				Expect(41 /* "TO" */);
				Expr(expr);
				if (la->kind == 61 /* "BY" */) {
					Get();
					ConstExpr(expr);
				}
				Expect(57 /* "DO" */);
				StatementSeq(forStatementSeq);
				Expect(33 /* "END" */);
				break;
			}
			case 62 /* "LOOP" */: {
				Get();
				StatementSeq(loopStatementSeq);
				Expect(33 /* "END" */);
				break;
			}
			case 63 /* "WITH" */: {
				Get();
				Guard();
				Expect(57 /* "DO" */);
				StatementSeq(statementSeq1);
				while (la->kind == 55 /* "|" */) {
					Get();
					Guard();
					Expect(57 /* "DO" */);
					StatementSeq(statementSeqN);
				}
				if (la->kind == 53 /* "ELSE" */) {
					Get();
					StatementSeq(statementSeqELSE);
				}
				Expect(33 /* "END" */);
				break;
			}
			case 64 /* "EXIT" */: {
				Get();
				break;
			}
			case 65 /* "RETURN" */: {
				Get();
				if (StartOf(8)) {
					Expr(expr);
				}
				break;
			}
			}
		}
}

void Parser::Case() {
		if (StartOf(8)) {
			CaseLabels();
			while (la->kind == 24 /* "," */) {
				Get();
				CaseLabels();
			}
			Expect(31 /* ":" */);
			StatementSeq(stmtSeq);
		}
}

void Parser::CaseLabels() {
		ExprRecord e1,e2; 
		ConstExpr(e1);
		if (la->kind == 42 /* ".." */) {
			Get();
			ConstExpr(e2);
		}
}

void Parser::Guard() {
		Qualident();
		Expect(31 /* ":" */);
		Qualident();
}

void Parser::SimpleExprAddOpClause(SimpleExprAddOpRecord &r) {
		AddOp(r.addOp);
		Term(r.term);
		if (StartOf(5)) {
			r.nullOrNextSimpleExprAddOpRecord=0; 
		} else if (la->kind == 15 /* "+" */ || la->kind == 16 /* "-" */ || la->kind == 17 /* "OR" */) {
			r.nullOrNextSimpleExprAddOpRecord=new SimpleExprAddOpRecord(); abortIfNull(r.nullOrNextSimpleExprAddOpRecord); 
			SimpleExprAddOpClause(*r.nullOrNextSimpleExprAddOpRecord);
		} else SynErr(98);
}

void Parser::Term(TermRecord &t) {
		t.factorPtr=0; 
		Factor(t.factorPtr);
		if (StartOf(11)) {
			t.nullOrNextTermMulOpRecord=0; 
		} else if (StartOf(12)) {
			t.nullOrNextTermMulOpRecord=new TermMulOpRecord(); abortIfNull(t.nullOrNextTermMulOpRecord); 
			TermMulOpClause(*t.nullOrNextTermMulOpRecord);
		} else SynErr(99);
}

void Parser::TermMulOpClause(TermMulOpRecord &r) {
		MulOp(r.mulOp);
		r.factorPtr=0; 
		Factor(r.factorPtr);
		if (StartOf(11)) {
			r.nullOrNextTermMulOpRecord=0; 
		} else if (StartOf(12)) {
			r.nullOrNextTermMulOpRecord=new TermMulOpRecord(); abortIfNull(r.nullOrNextTermMulOpRecord); 
			TermMulOpClause(*r.nullOrNextTermMulOpRecord);
		} else SynErr(100);
}

void Parser::Factor(FactorRecord *&factorPtr) {
		FactorRecord_DesignatorMaybeWithExprList *fd;
		FactorRecord_number *fn;
		FactorRecord_character *fc;
		FactorRecord_string *fs;
		FactorRecord_Set *fset;
		FactorRecord_Expr *fexpr;
		FactorRecord_tildeFactor *ftf;
		
		switch (la->kind) {
		case _ident: {
			factorPtr=fd=new FactorRecord_DesignatorMaybeWithExprList(); abortIfNull(factorPtr); 
			DesignatorMaybeWithExprList((*fd).r);
			break;
		}
		case _integer: case _real: {
			factorPtr=fn=new FactorRecord_number(); abortIfNull(factorPtr); 
			number((*fn).num);
			break;
		}
		case _character: {
			factorPtr=fc=new FactorRecord_character(); abortIfNull(factorPtr); 
			Character((*fc).ch);
			break;
		}
		case _string: {
			factorPtr=fs=new FactorRecord_string(); abortIfNull(factorPtr); 
			String((*fs).s);
			break;
		}
		case 43 /* "NIL" */: {
			factorPtr=new FactorRecord_NIL(); abortIfNull(factorPtr); 
			Get();
			break;
		}
		case 48 /* "{" */: {
			factorPtr=fset=new FactorRecord_Set(); abortIfNull(factorPtr); 
			Set((*fset).set);
			break;
		}
		case 35 /* "(" */: {
			factorPtr=fexpr=new FactorRecord_Expr(); abortIfNull(factorPtr); 
			Get();
			Expr((*fexpr).expr);
			Expect(36 /* ")" */);
			break;
		}
		case 44 /* "~" */: {
			factorPtr=ftf=new FactorRecord_tildeFactor(); abortIfNull(factorPtr); 
			ftf->factorPtr=0; 
			Get();
			Factor((*ftf).factorPtr);
			break;
		}
		default: SynErr(101); break;
		}
}

void Parser::DesignatorMaybeWithExprList(DesignatorMaybeWithExprListRecord &r) {
		IdentRec(r.identRec.ident_);
		if (StartOf(13)) {
			r.nullOrPtrToNextDesignatorMaybeWithExprListRepeatingPartRecord=0; 
		} else if (StartOf(14)) {
			r.nullOrPtrToNextDesignatorMaybeWithExprListRepeatingPartRecord=new DesignatorMaybeWithExprListRepeatingPartRecord(); 
			abortIfNull(r.nullOrPtrToNextDesignatorMaybeWithExprListRepeatingPartRecord);
			
			DesignatorMaybeWithExprListRepeatingPartClause(*(r.nullOrPtrToNextDesignatorMaybeWithExprListRepeatingPartRecord));
		} else SynErr(102);
}

void Parser::Character(wchar_t* &tok) {
		Expect(_character);
		tok = coco_string_create(t->val); 
}

void Parser::String(wchar_t* &tok) {
		Expect(_string);
		tok = coco_string_create(t->val); 
}

void Parser::Set(SetRecord &r) {
		r.nullOrPtrToNextSet=0; 
		Expect(48 /* "{" */);
		if (la->kind == 49 /* "}" */) {
			r.emptySet=true; 
		} else if (StartOf(8)) {
			r.emptySet=false; 
			Element(r.range);
			if (la->kind == 49 /* "}" */) {
			} else if (la->kind == 24 /* "," */) {
				r.nullOrPtrToNextSet=new SetRecord(); abortIfNull(r.nullOrPtrToNextSet); 
				ElementRangeList(*(r.nullOrPtrToNextSet));
			} else SynErr(103);
		} else SynErr(104);
		Expect(49 /* "}" */);
}

void Parser::DesignatorMaybeWithExprListRepeatingPartClause(DesignatorMaybeWithExprListRepeatingPartRecord &r) {
		if (la->kind == 45 /* "." */) {
			Get();
			IdentRec(r.clause1_identRec);
			r.clauseNumber=1; 
		} else if (la->kind == 46 /* "[" */) {
			Get();
			ExprList(r.clause2_exprList);
			Expect(47 /* "]" */);
			r.clauseNumber=2; 
		} else if (la->kind == 34 /* "^" */) {
			Get();
			r.clauseNumber=3; 
		} else if (la->kind == 35 /* "(" */) {
			Get();
			QualidentOrOptionalExprList(r.clause4_qualidentOrOptionalExprList);
			Expect(36 /* ")" */);
			r.clauseNumber=4; 
		} else SynErr(105);
		if (StartOf(13)) {
			r.nullOrPtrToNextDesignatorMaybeWithExprListRepeatingPartRecord=0; 
		} else if (StartOf(14)) {
			r.nullOrPtrToNextDesignatorMaybeWithExprListRepeatingPartRecord=new DesignatorMaybeWithExprListRepeatingPartRecord(); 
			abortIfNull(r.nullOrPtrToNextDesignatorMaybeWithExprListRepeatingPartRecord); 
			
			DesignatorMaybeWithExprListRepeatingPartClause(*(r.nullOrPtrToNextDesignatorMaybeWithExprListRepeatingPartRecord));
		} else SynErr(106);
}

void Parser::IdentRec(wchar_t* &tok) {
		Ident(tok);
}

void Parser::ExprList(ExprListRecord &r) {
		Expr(r.expr);
		if (la->kind == 36 /* ")" */ || la->kind == 47 /* "]" */) {
			r.nullOrCommaExprList=0; 
		} else if (la->kind == 24 /* "," */) {
			r.nullOrCommaExprList=new ExprListRecord(); abortIfNull(r.nullOrCommaExprList); 
			Get();
			ExprList(*(r.nullOrCommaExprList));
		} else SynErr(107);
}

void Parser::QualidentOrOptionalExprList(QualidentOrOptionalExprListRecord &r) {
		if (la->kind == 36 /* ")" */) {
			r.exprListPresent=false; 
		} else if (StartOf(8)) {
			r.exprListPresent=true; 
			ExprList(r.exprList);
		} else SynErr(108);
}

void Parser::ElementRangeList(SetRecord &r) {
		r.emptySet=false; r.nullOrPtrToNextSet=0; 
		Expect(24 /* "," */);
		Element(r.range);
		if (la->kind == 49 /* "}" */) {
			r.nullOrPtrToNextSet=0; 
		} else if (la->kind == 24 /* "," */) {
			r.nullOrPtrToNextSet=new SetRecord(); abortIfNull(r.nullOrPtrToNextSet); 
			ElementRangeList(*(r.nullOrPtrToNextSet));
		} else SynErr(109);
}

void Parser::Element(ElementRangeRecord &r) {
		Expr(r.expr1);
		if (la->kind == 24 /* "," */ || la->kind == 49 /* "}" */) {
			r.isrange=false; 
		} else if (la->kind == 42 /* ".." */) {
			r.isrange=true; 
			Get();
			Expr(r.expr2);
		} else SynErr(110);
}

void Parser::Module(ModuleRecord &r) {
		wchar_t *endName; 
		tab->OpenScope(); 
		Expect(66 /* "MODULE" */);
		Ident(r.moduleName);
		Expect(26 /* ";" */);
		if (StartOf(6)) {
			r.importListPtr=0; 
		} else if (la->kind == 25 /* "IMPORT" */) {
			r.importListPtr=new ImportListRecord(); abortIfNull(r.importListPtr); 
			ImportList(*(r.importListPtr));
		} else SynErr(111);
		DeclSeq(r.declSeq);
		if (la->kind == 32 /* "BEGIN" */) {
			Get();
			StatementSeq(stmtSeq);
		}
		Expect(33 /* "END" */);
		Ident(endName);
		if(!coco_string_equal(endName, r.moduleName)){
		Err(L"MODULE ident ... END ident.: idents do not match.");
		} 
		
		Expect(45 /* "." */);
		tab->CloseScope(); wprintf(L"MODULE %ls\n",name); coco_string_delete(name); gen->Emit(JMP, -1); 
		/*FILE_TYPE_ptr_address=gen->pc; gen->Emit(MODULE);*/ gen->Emit(0); 
		
}

void Parser::Integer(wchar_t* &tok) {
		Expect(_integer);
		tok = coco_string_create(t->val); 
}

void Parser::Real(wchar_t* &tok) {
		Expect(_real);
		tok = coco_string_create(t->val); 
}

void Parser::Oberon() {
		InitDeclarations(); modulePtr=new ModuleRecord(); abortIfNull(modulePtr); 
		Module(*(modulePtr));
}




// If the user declared a method Init and a mehtod Destroy they should
// be called in the contructur and the destructor respctively.
//
// The following templates are used to recognize if the user declared
// the methods Init and Destroy.

template<typename T>
struct ParserInitExistsRecognizer {
	template<typename U, void (U::*)() = &U::Init>
	struct ExistsIfInitIsDefinedMarker{};

	struct InitIsMissingType {
		char dummy1;
	};
	
	struct InitExistsType {
		char dummy1; char dummy2;
	};

	// exists always
	template<typename U>
	static InitIsMissingType is_here(...);

	// exist only if ExistsIfInitIsDefinedMarker is defined
	template<typename U>
	static InitExistsType is_here(ExistsIfInitIsDefinedMarker<U>*);

	enum { InitExists = (sizeof(is_here<T>(NULL)) == sizeof(InitExistsType)) };
};

template<typename T>
struct ParserDestroyExistsRecognizer {
	template<typename U, void (U::*)() = &U::Destroy>
	struct ExistsIfDestroyIsDefinedMarker{};

	struct DestroyIsMissingType {
		char dummy1;
	};
	
	struct DestroyExistsType {
		char dummy1; char dummy2;
	};

	// exists always
	template<typename U>
	static DestroyIsMissingType is_here(...);

	// exist only if ExistsIfDestroyIsDefinedMarker is defined
	template<typename U>
	static DestroyExistsType is_here(ExistsIfDestroyIsDefinedMarker<U>*);

	enum { DestroyExists = (sizeof(is_here<T>(NULL)) == sizeof(DestroyExistsType)) };
};

// The folloing templates are used to call the Init and Destroy methods if they exist.

// Generic case of the ParserInitCaller, gets used if the Init method is missing
template<typename T, bool = ParserInitExistsRecognizer<T>::InitExists>
struct ParserInitCaller {
	static void CallInit(T *t) {
		// nothing to do
	}
};

// True case of the ParserInitCaller, gets used if the Init method exists
template<typename T>
struct ParserInitCaller<T, true> {
	static void CallInit(T *t) {
		t->Init();
	}
};

// Generic case of the ParserDestroyCaller, gets used if the Destroy method is missing
template<typename T, bool = ParserDestroyExistsRecognizer<T>::DestroyExists>
struct ParserDestroyCaller {
	static void CallDestroy(T *t) {
		// nothing to do
	}
};

// True case of the ParserDestroyCaller, gets used if the Destroy method exists
template<typename T>
struct ParserDestroyCaller<T, true> {
	static void CallDestroy(T *t) {
		t->Destroy();
	}
};

void Parser::Parse() {
	t = NULL;
	la = dummyToken = new Token();
	la->val = coco_string_create(L"Dummy Token");
	Get();
	Oberon();
	Expect(0);
}

Parser::Parser(Scanner *scanner) {
	//parserListener=0;
	maxT = 67;

	ParserInitCaller<Parser>::CallInit(this);
	dummyToken = NULL;
	t = la = NULL;
	minErrDist = 2;
	errDist = minErrDist;
	this->scanner = scanner;
	errors = new Errors();
}

bool Parser::StartOf(int s) {
	const bool T = true;
	const bool x = false;

	static bool set[15][69] = {
		{T,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x},
		{x,x,x,x, x,x,x,T, T,T,T,T, T,T,T,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x},
		{x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,T, T,x,T,x, x,x,x,T, x,T,x,x, T,x,T,x, x,T,T,x, x,x,x,T, x,T,x,T, T,T,x,T, x,T,x,T, x,T,x,x, x,x,x,x, x},
		{x,T,x,T, T,T,T,x, x,x,x,x, x,x,x,T, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,T, x,x,x,x, x,x,x,T, T,x,x,x, T,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x},
		{x,T,x,T, T,T,T,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,T, x,x,x,x, x,x,x,T, T,x,x,x, T,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x},
		{x,x,x,x, x,x,x,T, T,T,T,T, T,T,T,x, x,x,x,x, x,x,x,T, T,x,T,x, x,x,x,T, x,T,x,x, T,x,T,x, x,T,T,x, x,x,x,T, x,T,x,T, T,T,x,T, x,T,x,T, x,T,x,x, x,x,x,x, x},
		{x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,T, T,T,T,x, T,T,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x},
		{x,x,x,x, x,x,x,T, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, T,x,T,x, x,x,x,T, x,x,x,T, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x},
		{x,T,x,T, T,T,T,x, x,x,x,x, x,x,x,T, T,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,T, x,x,x,x, x,x,x,T, T,x,x,x, T,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x},
		{x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,T,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, T,T,x,T, x,x,x,T, x,x,x,x, x,x,x,x, x},
		{x,T,x,T, T,T,T,x, x,x,x,x, x,x,x,T, T,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,T, x,x,x,x, x,x,x,T, T,x,x,x, T,x,T,x, x,x,T,x, T,x,T,x, T,x,T,T, T,T,x,x, x},
		{x,x,x,x, x,x,x,T, T,T,T,T, T,T,T,T, T,T,x,x, x,x,x,T, T,x,T,x, x,x,x,T, x,T,x,x, T,x,T,x, x,T,T,x, x,x,x,T, x,T,x,T, T,T,x,T, x,T,x,T, x,T,x,x, x,x,x,x, x},
		{x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,T,T, T,T,T,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x},
		{x,x,x,x, x,x,x,T, T,T,T,T, T,T,T,T, T,T,T,T, T,T,T,T, T,x,T,x, x,x,x,T, x,T,x,x, T,x,T,x, x,T,T,x, x,x,x,T, x,T,x,T, T,T,x,T, x,T,x,T, x,T,x,x, x,x,x,x, x},
		{x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,T,T, x,x,x,x, x,x,x,x, x,T,T,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x}
	};



	return set[s][la->kind];
}

Parser::~Parser() {
	ParserDestroyCaller<Parser>::CallDestroy(this);
	delete errors;
	delete dummyToken;
}

Errors::Errors() {
	count = 0;
}

void Errors::SynErr(int line, int col, int n) {
	wchar_t* s;
	switch (n) {
			case 0: s = coco_string_create(L"EOF expected"); break;
			case 1: s = coco_string_create(L"ident expected"); break;
			case 2: s = coco_string_create(L"badString expected"); break;
			case 3: s = coco_string_create(L"string expected"); break;
			case 4: s = coco_string_create(L"integer expected"); break;
			case 5: s = coco_string_create(L"real expected"); break;
			case 6: s = coco_string_create(L"character expected"); break;
			case 7: s = coco_string_create(L"\"=\" expected"); break;
			case 8: s = coco_string_create(L"\"#\" expected"); break;
			case 9: s = coco_string_create(L"\"<\" expected"); break;
			case 10: s = coco_string_create(L"\"<=\" expected"); break;
			case 11: s = coco_string_create(L"\">\" expected"); break;
			case 12: s = coco_string_create(L"\">=\" expected"); break;
			case 13: s = coco_string_create(L"\"IN\" expected"); break;
			case 14: s = coco_string_create(L"\"IS\" expected"); break;
			case 15: s = coco_string_create(L"\"+\" expected"); break;
			case 16: s = coco_string_create(L"\"-\" expected"); break;
			case 17: s = coco_string_create(L"\"OR\" expected"); break;
			case 18: s = coco_string_create(L"\"*\" expected"); break;
			case 19: s = coco_string_create(L"\"/\" expected"); break;
			case 20: s = coco_string_create(L"\"DIV\" expected"); break;
			case 21: s = coco_string_create(L"\"MOD\" expected"); break;
			case 22: s = coco_string_create(L"\"&\" expected"); break;
			case 23: s = coco_string_create(L"\":=\" expected"); break;
			case 24: s = coco_string_create(L"\",\" expected"); break;
			case 25: s = coco_string_create(L"\"IMPORT\" expected"); break;
			case 26: s = coco_string_create(L"\";\" expected"); break;
			case 27: s = coco_string_create(L"\"CONST\" expected"); break;
			case 28: s = coco_string_create(L"\"TYPE\" expected"); break;
			case 29: s = coco_string_create(L"\"VAR\" expected"); break;
			case 30: s = coco_string_create(L"\"PROCEDURE\" expected"); break;
			case 31: s = coco_string_create(L"\":\" expected"); break;
			case 32: s = coco_string_create(L"\"BEGIN\" expected"); break;
			case 33: s = coco_string_create(L"\"END\" expected"); break;
			case 34: s = coco_string_create(L"\"^\" expected"); break;
			case 35: s = coco_string_create(L"\"(\" expected"); break;
			case 36: s = coco_string_create(L"\")\" expected"); break;
			case 37: s = coco_string_create(L"\"ARRAY\" expected"); break;
			case 38: s = coco_string_create(L"\"OF\" expected"); break;
			case 39: s = coco_string_create(L"\"RECORD\" expected"); break;
			case 40: s = coco_string_create(L"\"POINTER\" expected"); break;
			case 41: s = coco_string_create(L"\"TO\" expected"); break;
			case 42: s = coco_string_create(L"\"..\" expected"); break;
			case 43: s = coco_string_create(L"\"NIL\" expected"); break;
			case 44: s = coco_string_create(L"\"~\" expected"); break;
			case 45: s = coco_string_create(L"\".\" expected"); break;
			case 46: s = coco_string_create(L"\"[\" expected"); break;
			case 47: s = coco_string_create(L"\"]\" expected"); break;
			case 48: s = coco_string_create(L"\"{\" expected"); break;
			case 49: s = coco_string_create(L"\"}\" expected"); break;
			case 50: s = coco_string_create(L"\"IF\" expected"); break;
			case 51: s = coco_string_create(L"\"THEN\" expected"); break;
			case 52: s = coco_string_create(L"\"ELSIF\" expected"); break;
			case 53: s = coco_string_create(L"\"ELSE\" expected"); break;
			case 54: s = coco_string_create(L"\"CASE\" expected"); break;
			case 55: s = coco_string_create(L"\"|\" expected"); break;
			case 56: s = coco_string_create(L"\"WHILE\" expected"); break;
			case 57: s = coco_string_create(L"\"DO\" expected"); break;
			case 58: s = coco_string_create(L"\"REPEAT\" expected"); break;
			case 59: s = coco_string_create(L"\"UNTIL\" expected"); break;
			case 60: s = coco_string_create(L"\"FOR\" expected"); break;
			case 61: s = coco_string_create(L"\"BY\" expected"); break;
			case 62: s = coco_string_create(L"\"LOOP\" expected"); break;
			case 63: s = coco_string_create(L"\"WITH\" expected"); break;
			case 64: s = coco_string_create(L"\"EXIT\" expected"); break;
			case 65: s = coco_string_create(L"\"RETURN\" expected"); break;
			case 66: s = coco_string_create(L"\"MODULE\" expected"); break;
			case 67: s = coco_string_create(L"??? expected"); break;
			case 68: s = coco_string_create(L"invalid number"); break;
			case 69: s = coco_string_create(L"invalid Relation"); break;
			case 70: s = coco_string_create(L"invalid AddOp"); break;
			case 71: s = coco_string_create(L"invalid MulOp"); break;
			case 72: s = coco_string_create(L"invalid Expr"); break;
			case 73: s = coco_string_create(L"invalid SimpleExpr"); break;
			case 74: s = coco_string_create(L"invalid SimpleExpr"); break;
			case 75: s = coco_string_create(L"invalid ModuleImportEntry"); break;
			case 76: s = coco_string_create(L"invalid ModuleImportEntryList"); break;
			case 77: s = coco_string_create(L"invalid DeclSeqConstDeclListMandatory"); break;
			case 78: s = coco_string_create(L"invalid DeclSeqConstDeclList"); break;
			case 79: s = coco_string_create(L"invalid DeclSeqTypeDeclListMandatory"); break;
			case 80: s = coco_string_create(L"invalid DeclSeqTypeDeclList"); break;
			case 81: s = coco_string_create(L"invalid DeclSeqVarDeclListMandatory"); break;
			case 82: s = coco_string_create(L"invalid DeclSeqVarDeclList"); break;
			case 83: s = coco_string_create(L"invalid DeclSeqConstTypeVarListMandatory"); break;
			case 84: s = coco_string_create(L"invalid DeclSeqConstTypeVarListMandatory"); break;
			case 85: s = coco_string_create(L"invalid DeclSeqConstTypeVarList"); break;
			case 86: s = coco_string_create(L"invalid DeclSeqProcDeclFwdDeclListMandatory"); break;
			case 87: s = coco_string_create(L"invalid DeclSeqProcDeclFwdDeclListMandatory"); break;
			case 88: s = coco_string_create(L"invalid ProcDecl"); break;
			case 89: s = coco_string_create(L"invalid DeclSeqProcDeclFwdDeclList"); break;
			case 90: s = coco_string_create(L"invalid IdentDef"); break;
			case 91: s = coco_string_create(L"invalid Type"); break;
			case 92: s = coco_string_create(L"invalid IdentList"); break;
			case 93: s = coco_string_create(L"invalid OptionalReceiver"); break;
			case 94: s = coco_string_create(L"invalid Receiver"); break;
			case 95: s = coco_string_create(L"invalid OptionalFormalPars"); break;
			case 96: s = coco_string_create(L"invalid StatementSeq"); break;
			case 97: s = coco_string_create(L"invalid FieldList"); break;
			case 98: s = coco_string_create(L"invalid SimpleExprAddOpClause"); break;
			case 99: s = coco_string_create(L"invalid Term"); break;
			case 100: s = coco_string_create(L"invalid TermMulOpClause"); break;
			case 101: s = coco_string_create(L"invalid Factor"); break;
			case 102: s = coco_string_create(L"invalid DesignatorMaybeWithExprList"); break;
			case 103: s = coco_string_create(L"invalid Set"); break;
			case 104: s = coco_string_create(L"invalid Set"); break;
			case 105: s = coco_string_create(L"invalid DesignatorMaybeWithExprListRepeatingPartClause"); break;
			case 106: s = coco_string_create(L"invalid DesignatorMaybeWithExprListRepeatingPartClause"); break;
			case 107: s = coco_string_create(L"invalid ExprList"); break;
			case 108: s = coco_string_create(L"invalid QualidentOrOptionalExprList"); break;
			case 109: s = coco_string_create(L"invalid ElementRangeList"); break;
			case 110: s = coco_string_create(L"invalid Element"); break;
			case 111: s = coco_string_create(L"invalid Module"); break;

		default:
		{
			wchar_t format[20];
			coco_swprintf(format, 20, L"error %d", n);
			s = coco_string_create(format);
		}
		break;
	}
	wprintf(L"-- line %d col %d: %ls\n", line, col, s);
	coco_string_delete(s);
	count++;
}

void Errors::Error(int line, int col, const wchar_t *s) {
	wprintf(L"-- line %d col %d: %ls\n", line, col, s);
	count++;
}

void Errors::Warning(int line, int col, const wchar_t *s) {
	wprintf(L"-- line %d col %d: %ls\n", line, col, s);
}

void Errors::Warning(const wchar_t *s) {
	wprintf(L"%ls\n", s);
}

void Errors::Exception(const wchar_t* s) {
	wprintf(L"%ls", s); 
	exit(1);
}

} // namespace

