/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_alpha_gui_ContactListWindowImpl */

#ifndef _Included_org_alpha_gui_ContactListWindowImpl
#define _Included_org_alpha_gui_ContactListWindowImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_alpha_gui_ContactListWindowImpl
 * Method:    createWindow_getHWND
 * Signature: ()I
 */
JNIEXPORT jint Java_org_alpha_gui_ContactListWindowImpl_createWindow_1getHWND
  (JNIEnv *, jclass);

/*
 * Class:     org_alpha_gui_ContactListWindowImpl
 * Method:    getActiveWindowHWND
 * Signature: ()I
 */
JNIEXPORT jint Java_org_alpha_gui_ContactListWindowImpl_getActiveWindowHWND
  (JNIEnv *, jclass);

/*
 * Class:     org_alpha_gui_ContactListWindowImpl
 * Method:    getForegroundWindowHWND
 * Signature: ()I
 */
JNIEXPORT jint Java_org_alpha_gui_ContactListWindowImpl_getForegroundWindowHWND
  (JNIEnv *, jclass);

/*
 * Class:     org_alpha_gui_ContactListWindowImpl
 * Method:    hideWindow
 * Signature: (I)V
 */
JNIEXPORT void Java_org_alpha_gui_ContactListWindowImpl_hideWindow
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_alpha_gui_ContactListWindowImpl
 * Method:    showWindow
 * Signature: (I)V
 */
JNIEXPORT void Java_org_alpha_gui_ContactListWindowImpl_showWindow
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_alpha_gui_ContactListWindowImpl
 * Method:    setForeground0
 * Signature: (I)V
 */
JNIEXPORT void Java_org_alpha_gui_ContactListWindowImpl_setForeground0
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
